Repository 26B/unbabble, pull requests merged in 2024-07, with the labels that each got.

#60 Fix missing transient deletes on source updates/deletes
  lib/LangInterface.php
Labels: bug

#68 Fix SQL bug in LangInterface::get_terms_for_source
  lib/LangInterface.php
Labels: bug

#76 Fix hidden languages routing - checking user session
  CHANGELOG.md
  lib/LangInterface.php
Labels: bug

#43 Fetch options for another blog on multisite
  CHANGELOG.md
  lib/Options.php
Labels: enhancement

#77 Several Improvements
  CHANGELOG.md
  build/index.asset.php
  build/index.js
  build/index.js.map
  lib/API/Gutenberg/Post.php
  lib/Admin/Customize.php
  lib/Admin/LanguageSwitcher.php
  lib/Admin/Redirector.php
  lib/Plugin.php
  lib/Posts/AdminNotices.php
  lib/Posts/EditFilters.php
  lib/Posts/LangFilter.php
  lib/Terms/AdminNotices.php
  lib/Terms/EditFilters.php
  lib/Terms/LangFilter.php
  lib/Terms/LangMetaBox.php
  src/scripts/components/LanguagePanel/Content.jsx
  src/scripts/components/LanguagePanel/PostLanguage.jsx
Labels: bug

#51 ElasticPress Integration
  CHANGELOG.md
  lib/Integrations/ElasticPress.php
  lib/Plugin.php
  lib/Posts/LangFilter.php
Labels: enhancement

#81 Fix bad language check condition for lang meta box
  CHANGELOG.md
  lib/Terms/LangMetaBox.php
Labels: bug

#86 Add `wp-env` for local development
  .nvmrc
  .wp-env.json
  CHANGELOG.md
  README.md
  build/index.asset.php
  build/index.js
  lib/API/Gutenberg/Post.php
  lib/LangInterface.php
  package-lock.json
  package.json
  src/index.js
  unbabble.php
Labels: bug, documentation, enhancement

#90 Stop customize hooks when nav_menu are not translatable
  lib/Admin/Customize.php
  lib/Options.php
Labels: bug

#95 Fix bulk edit and edit no language filter
  CHANGELOG.md
  lib/Posts/BulkEdit.php
  lib/Posts/EditFilters.php
Labels: bug

#92 Fix nav_menu's language change and translation create
  CHANGELOG.md
  lib/Admin/Customize.php
  lib/LangInterface.php
  lib/Terms/ChangeLanguage.php
  lib/Terms/CreateTranslation.php
Labels: bug

#93 Fix Directory routing when there are arguments right after the directory
  CHANGELOG.md
  lib/Router/Directory.php
Labels: bug

#98 Fix post type in url on create translation
  CHANGELOG.md
  build/index.asset.php
  build/index.js
  lib/Admin/Admin.php
  src/scripts/components/LanguagePanel/CreateTranslations.jsx
Labels: bug
